
export const REQUEST_LOAD_SEATS = 'LOAD_SEATS';

export const LOAD_SEAT_SUCCESS = 'LOAD_SEAT_SUCCESS';

export const REQUEST_SELECT_SEAT = 'REQUEST_SELECT_SEAT';

export const SELECT_SEAT_SUCCESS = 'SELECT_SEAT_SUCCESS';

export const REQUEST_DESELECT_SEAT = 'REQUEST_DESELECT_SEAT';

export const DESELECT_SEAT_SUCCESS = 'DESELECT_SEAT_SUCCESS';

export const CALCULATE_AMOUNT = 'CALCULATE_AMOUNT';
